# Do not edit this file; it will be overwritten on upgrades.
# If you want to override the settings here, you can copy this file
# to /etc/tmpfiles.d/mariadb.conf and make your changes there.

d /var/run/mariadb 0755 mysql mysql -
